# Generated by Django 5.2.4 on 2025-07-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_comment_is_edited_comment_toxicity_label_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="approved",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="toxic",
        ),
        migrations.AddField(
            model_name="comment",
            name="status",
            field=models.CharField(
                choices=[
                    ("approved", "Approved"),
                    ("pending_review", "Pending Review"),
                    ("rejected", "Rejected"),
                ],
                default="approved",
                max_length=20,
            ),
        ),
    ]
