# Generated by Django 5.2.4 on 2025-07-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_genre_post_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="status",
            field=models.CharField(
                choices=[
                    ("approved", "Approved"),
                    ("pending_review", "Pending Review"),
                    ("reported", "Reported"),
                    ("rejected", "Rejected"),
                ],
                default="approved",
                max_length=20,
            ),
        ),
    ]
