# Generated by Django 5.2.4 on 2025-07-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(default="Sanity Check", max_length=100)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logo/")),
                (
                    "favicon",
                    models.ImageField(blank=True, null=True, upload_to="logo/"),
                ),
            ],
            options={
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
